analyzer:
  errors:
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    unnecessary_new: ignore
    unnecessary_overrides: ignore
    use_super_parameters: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
