analyzer:
  errors:
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    no_wildcard_variable_uses: ignore
    unnecessary_new: ignore
    unnecessary_overrides: ignore
    unnecessary_to_list_in_spreads: ignore
    use_super_parameters: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
