name: simanis
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  animator: ^3.1.0
  camerawesome: ^1.4.0
  carousel_slider: ^4.2.1
  charts_flutter_new: ^0.12.0
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  file_picker: ^6.1.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_downloader: ^1.11.4
  flutter_image_compress: ^2.1.0
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^16.1.0
  flutter_native_splash: ^2.3.5
  flutter_pdfview: ^1.3.2
  flutter_timezone: ^1.0.8
  fluttertoast: ^8.2.6
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.12.0
  lazyui: ^1.0.21
  masonry_grid: ^1.0.0
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  platform: ^3.1.3
  qr_flutter: ^4.1.0
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_calendar: ^20.4.50
  url_launcher: ^6.2.1

dependency_overrides:
  intl: ^0.18.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/t_splash.png
    - assets/images/profile.png
    - assets/images/blood.png
    - assets/images/foot.png
    - assets/images/medicine.png
    - assets/images/book.png
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/intro4.png
    - assets/images/svg/rating.svg

flutter_native_splash:
  color: "#ffffff"
  color_dark: '#ffffff'
  image: assets/images/t_splash.png
  image_dark: assets/images/t_splash.png

  android_12:
    image: assets/images/t_splash.png
    image_dark: assets/images/t_splash.png
    color: "#ffffff"
    color_dark: '#ffffff'
