// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXQLFKOLjllYVqny2qzSq2ZuaK3AQTIU',
    appId: '1:749495190126:web:99b2967584476910685c7f',
    messagingSenderId: '749495190126',
    projectId: 'simanis-e9321',
    authDomain: 'simanis-e9321.firebaseapp.com',
    storageBucket: 'simanis-e9321.appspot.com',
    measurementId: 'G-SNW8PX2KRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_S0vyeUI3zIQOyzMUM-_PssNNDWyLh0',
    appId: '1:749495190126:android:ec437242d044ca93685c7f',
    messagingSenderId: '749495190126',
    projectId: 'simanis-e9321',
    storageBucket: 'simanis-e9321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD3G06_3Eois3TYY1P1arplvqBexiwocA',
    appId: '1:749495190126:ios:692d02c0f9c8c951685c7f',
    messagingSenderId: '749495190126',
    projectId: 'simanis-e9321',
    storageBucket: 'simanis-e9321.appspot.com',
    iosBundleId: 'com.ayu.simanis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD3G06_3Eois3TYY1P1arplvqBexiwocA',
    appId: '1:749495190126:ios:692d02c0f9c8c951685c7f',
    messagingSenderId: '749495190126',
    projectId: 'simanis-e9321',
    storageBucket: 'simanis-e9321.appspot.com',
    iosBundleId: 'com.ayu.simanis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARXQLFKOLjllYVqny2qzSq2ZuaK3AQTIU',
    appId: '1:749495190126:web:7187d1d4b9f01022685c7f',
    messagingSenderId: '749495190126',
    projectId: 'simanis-e9321',
    authDomain: 'simanis-e9321.firebaseapp.com',
    storageBucket: 'simanis-e9321.appspot.com',
    measurementId: 'G-0705NL4WC5',
  );
}
